### ISSUE TITLE
Uncaught exception when pushing

### ISSUE THREAD

**Issue by eobanb** [publicmediaplatform/pmp-wordpress#115]
PHP error is as follows:

Fatal error: Uncaught exception 'Pmp\Sdk\Exception\LinkException' with message 'Unable to retrieve urn:collectiondoc:form:issuetoken from the home document' in /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php:95 Stack trace: #0 /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(75): Pmp\Sdk\AuthClient->_authLink('urn:collectiond...', Array) #1 /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(46): Pmp\Sdk\AuthClient->_request('urn:collectiond...', Array) #2 /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(34): Pmp\Sdk\AuthClient->getToken() #3 /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk.php(62): Pmp\Sdk\AuthClient->__construct(NULL, NULL, NULL, Object(Pmp\Sdk\CollectionDocJson)) #4 /www/indpub/wp-content/plugins/pub in /www/indpub/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php on line 95

**Comment by eobanb** [comment]
This is with pmp-wordpress release 0.2.8, PHP 5.4.16, and Wordpress 3.9.3.

**Comment by cavis** [comment]
Does search-for/pulling content work on that server?

**Comment by eobanb** [comment]
Yep, search/pull works fine.

**Comment by eobanb** [comment]
Any new ideas on this? We are hoping to get push working as soon as we can.

**Comment by rnagle** [comment]
@eobanb If you downloaded the plugin via Github or are tracking the plugin using Git and haven't updated Composer requirements lately, I would try that first. From the directory you installed PMP plugin into, try running the following command:

    composer install

If you downloaded the plugin via [WordPress.org](https://wordpress.org/plugins/public-media-platform/), you should already have all requirements satisfied (these files live in the `vendor` directory).

Based on the error you've described, it seems like the plugin is getting hung up on retrieving some basic information from the API when it first requests a handle.

Can you access the "Home" document directly (for [live](https://api.pmp.io/) and [sandbox](https://api-sandbox.pmp.io/) versions of the API) to verify they are working properly? If yes, you'll notice that the same `urn:collectiondoc:form:issuetoken` from the exception you shared is included in the Home document.

Being unable to access the Home document for some reason (maybe some temporary network connectivity issue?) could conceivably cause this issue.

If it turns out to be a permissions issue with your API credentials, you'll need to talk to someone at PMP or NPR. @cavis can you recommend anyone?

**Comment by eobanb** [comment]
@rnagle we're using a copy downloaded from the wordpress.org plugin directory.

Other than accessing the home document from my browser (it appears to download just fine, and I see urn:collectiondoc:form:issuetoken referenced near the end) is there something else I should be doing?

This has happened weeks/months apart and very consistently so I don't think any temporary network issue is the problem.

**Comment by rnagle** [comment]
@eobanb Thanks for clarifying those points. It sounds like you have everything in order. A few more thoughts for you...

Have you tried to replicate the issue on multiple servers/hosts? For instance, if it works fine on a local development (or staging, test, etc.) site, that would point to a problem with the host that the live site is deployed to.

If you are able to replicate the problem on another host, then I would definitely want to investigate the permissions for your API credentials to see if the problem originates there.

**Comment by cavis** [comment]
Looks like i'm late to the party!

I'm pretty sure this is tied to a specific server setup, rather than an API/credentials problem.  That `Pmp\Sdk\Exception\LinkException` will really only occur if you somehow authenticate with the API _before_ fetching the home-document.  (I thought the SDK prevented this scenario, so I'm very curious where this originates in the `pmp-wordpress` codebase).

Maybe somewhere in the codebase, it tries to create-and-save a PMP doc without fetching the home doc?  But why it would only impact your specific setup, i have no clue.

@rnagle have you ever tried running the plugin against a 3.9.x Wordpress?  I'm pretty sure I have not - and the unit tests have always been against a 4.x.  Could there be any differences there?

**Comment by rnagle** [comment]
@cavis Thanks for the information.

I've been using 4.x+ for development and testing.

I don't think that WordPress' settings API (used to store/retrieve the PMP API credentials) has changed so much that it would cause invalid parameters to be passed to the `\Pmp\Sdk` constructor.

There are two places in the code base where the SDK is instantiated if you're interested in checking that out: [here](https://github.com/publicmediaplatform/pmp-wordpress/blob/417818b31e4d07a919f013cd8cc3ed91c5efddba/inc/notifications.php#L74-L83) and [here](https://github.com/publicmediaplatform/pmp-wordpress/blob/417818b31e4d07a919f013cd8cc3ed91c5efddba/inc/class-sdkwrapper.php#L13-L19).

As far as I know, the plugin *always* uses the SDK to access the API.

The only other place it communicates with the PMP is [during the notification subscription process](https://github.com/publicmediaplatform/pmp-wordpress/blob/417818b31e4d07a919f013cd8cc3ed91c5efddba/inc/notifications.php#L87-L100).

We could try adding a 3.9.x configuration to the `travis.yml` file to see if the unit tests reveal anything. What do you think?

**Comment by eobanb** [comment]
OK, I have a 4.0.x install up and running (same PHP and plugin versions), same exact error.

**Comment by eobanb** [comment]
New update: I've disabled every single plugin on our testing site and determined there's a conflict with this plugin:

https://wordpress.org/plugins/wordpress-mu-sitewide-tags/

Given that the above plugin hasn't been updated in a couple years, I'm going to go ahead and assume the best thing to do here would be figuring out how to discontinue our site's use of it.

**Comment by jackbrighton** [comment]
That...is very good to know! Very glad you got it sorted out.
