### ISSUE TITLE
Missing images in search results

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#16]
Sometimes images are not showing up next to their story in the results list.

For example, see [this story](https://support.pmp.io/search?text=%22Beautiful%20photos%20of%20everyday%20life%22&profile=story&has=image) on the support site.

Then search for guid `83b6d846-d6ae-4b74-ac3a-8992e7dea39d` in the plugin (an NPR story in api-production).  The image is missing.

**Comment by cavis** [comment]
Also seeing on some PRX content, such as - https://support.pmp.io/search?text=%221405%3A%20Cops%2C%20Dumpster%20Diving%2C%20and%20Mental%20Illness%22&profile=story

**Comment by cavis** [comment]
Note: this bug probably also affects featured images.

**Comment by cavis** [comment]
Another note: for some PRI's The World stories, you can probably expect to see `null` images in the attached items.  These are Reuter's images that you don't have permission to use.  (But the support site WILL show them, as it runs as an all-access user).

**Comment by rnagle** [comment]
It looks like this is happening because the only enclosures available for the stories mentioned do not match any of the crop sizes that we give preference. See: https://github.com/publicmediaplatform/pmp-wordpress/blob/master/assets/js/pmp.js#L102

For the first example, I'm only seeing crops `enlargement` and `custom`. For the PRX example, only `medium`.

So, it sounds like we need a more robust fallback strategy here.

Also interesting to note -- despite there being no thumbnail shown in the search results, creating a draft based on the PRX story example does result in a featured image being pulled in. This is not the case for the first example, though. Is this what you're referring to when you say this bug probably also affects featured images?

**Comment by cavis** [comment]
My strategy has been to start with a list of "known" crops, then if you can't match one of those, just grab the first image 'links.enclosure[0].href` as a backup.

I think I was just guessing that the "featured image" code would have the same problem.  But maybe it doesn't.

**Comment by rnagle** [comment]
Excellent. Makes sense to me.

I believe this is fixed now. See: c061dba7340db3af467cc14150fbdd9f98787029.

Also see sort-of related: 89add440795ae0de1f869b1fce0a43149207cc0b. I added this because I noticed a `max_input_vars` warning when sending info to the server as url encoded form data. This fixes an issue where, when creating a draft or publishing a post, everything except for the featured image makes its way into WordPress.
