### ISSUE TITLE
Revoked access to PMP stories

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#2]
What happens if:

1. WP-User pulls a PMP story locally, with update-polling enabled
2. PMP-publisher deletes story, or removes permissions from it
3. WP update-poll tries to check story for changes - gets 404 or 403

In theory, the post should be deleted from Wordpress, or at least un-published.  Best case: it would somehow notify the WP-User about this, before just automatically nuking something from their site.

**Comment by cavis** [comment]
For now, let's just delete the Post without prompting the user.  It's now in the PMP Terms-of-Use that clients must remove content from their apps if the publisher removes their access to it.

**Comment by rnagle** [comment]
Fixed with 46be24b1435baf7642ff77103d75017bab45e928.

**Comment by cavis** [comment]
This may be getting into the weeds - but what happens to any media that came with that Post?

**Comment by rnagle** [comment]
The cron task that checks for updates will also check for updates to any media pulled from the PMP API, since these items also have `pmp_guid` specified.

So, the media item will, at the very least, be orphaned in WordPress since it can't be associated with a deleted post. If the permissions for the media item are the same as the post that was deleted, the media item will be deleted.

**Comment by cavis** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/1410587/8093783/420becea-0f80-11e5-92bb-589f6bc8ef90.png)
