### ISSUE TITLE
Unable to push to PMP

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#45]
Attempting to save a Post: http://wordpress.pmpdev.org/?p=66

When I click "Update and push to PMP", the changes to the WP Post are saved.  But I'm sent to a blank white screen, and the content does NOT make it to the PMP.  PHP log shows:

```
[Mon Apr 20 15:07:59 2015] [error] [client 70.59.38.130] PHP Fatal error:  Call to undefined method stdClass::save() in /var/www/html/wp-content/plugins/pmp-wordpress-master/inc/functions.php on line 250, referer: http://wordpress.pmpdev.org/wp-admin/post.php?post=66&action=edit
```

Any ideas?

**Comment by cavis** [comment]
Update: this seems tied to which featured image I pick.

1. Picking a featured-image downloaded by a previous version of the plugin
 * I get that `Call to undefined method stdClass::save()` error
2. Picking a featured-image downloaded by the current-master version of the plugin
 * I get a `Uncaught Pmp\\Sdk\\Exception\\NotFoundException: [403]: Forbidden` error
 * Happens when the plugin attempts to PUT an image-doc that I don't own (it's the image that was pulled down from the PMP`
3. Picking a featured-image that I uploaded
 * Works fine

**Comment by cavis** [comment]
Are featured images tied to the Post, or the Media item?  I'm sort of thinking they should be tied to the specific Post.

For instance, I create 2 Posts using the same featured image from my Media Library.  After pushing both Posts to the PMP, I should end up with 2 Story-docs and 2 Image-docs in the PMP.  If I change the featured image on one Post, it should just update 1 of those existing Image-docs to have different enclosure links.

**Comment by rnagle** [comment]
Couple things:

1. We can try filtering the media picker so that images that you do not own are not available to link with stories/posts. This seems like it might be an edge case, but filtering the list may be easy enough that we should just do it. This *should* fix numbers 1 and 2 in your comment above.
2. Regarding the relationships between media and story docs -- I think creating a new Doc each time an image is attached to a story will cause problems unless we actually duplicate the image in WordPress so that it can be assigned its own PMP GUID. Maybe we need to take it a step further and filter out ANY images that have been attached to posts and pushed to the PMP. Users would then have to re-upload an image to attach it to a post. This would ensure a unique image-to-post relationship on both the WP and PMP sides.

**Comment by rnagle** [comment]
I managed to set up a filter for the media library, which will exclude any media items that exist in the PMP and do not belong to the current user. See: 5430e961d7a7b0eb985046c7de1bfa3d3e62a4d7. This should mean the original issue of being unable to push to PMP is fixed.

Perhaps we should open a new ticket for more discussion around the other issues?

**Comment by cavis** [comment]
Agreed.  Opened #57.
